theme = "tokyonight"

[editor]
line-number = "relative"
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-d = ["half_page_down", "align_view_center"]
C-u = ["half_page_up", "align_view_center"]

[keys.insert]
j = {k = "normal_mode"}
C-e = ["insert_at_line_end"]
C-o = ["insert_at_line_end", "open_below"]
A-O = ["open_above"]




